name: pdf-to-searchable
runtime: python3.9
build:
  - pip install -r requirements.txt
services:
  - name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  - name: pdf-to-searchable
    file: tess.py
    entrypoint: app
    http:
      path: /convert
      method: post
    depends_on:
      - nginx
  - name: pdf-to-searchable-text
    file: tess.py
    entrypoint: app
    http:
      path: /extract_text
      method: post
    depends_on:
      - nginx
